version: '3.8'

services:
  # Base de datos PostgreSQL para el Auth-Service
  postgres-db:
    image: postgres:16-alpine
    container_name: uce_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: uce_wellness_db
    ports:
      - "5432:5432"
    networks:
      - wellness-net

networks:
  wellness-net:
    driver: bridge