version: '3.8'

services:
  # Base de datos PostgreSQL para el Auth-Service
  postgres-db:
    image: postgres:16-alpine
    container_name: uce_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: uce_wellness_db
    ports:
      - "5432:5432"
    networks:
      - wellness-net

  # NUEVA: Base de datos para Assessments (MongoDB)
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  wellness-net:
    driver: bridge